- web/.gitignore
- web/gen/js/.gitignore
- web/gen/json/.gitignore
- web/gen/json_full/.gitignore
- web/gen/smarty/templates_c/.gitignore
In GitLab by @hsheth2 on Sep 23, 2019, 21:08
This should allow us to directly clone the repo and start docker without any permission issues.
> Update web/gen folder permissions

- web/WorksheetActions.php
Resolves the following error message:
`2019/12/03 14:55:35 [error] 1346#1346: *284747 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: ociId in /home/web/app/web/WorksheetActions.php on line 175" while reading response header from upstream, client: <clip>, server: coursetable.com, request: "GET /WorksheetActions.php?action=get&season=202001 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "coursetable.com", referrer: "https://coursetable.com/Table/202001"`
> Fix bug in worksheet actions

- frontend/src/queries/QueryStrings.js
-add back professor_info to query (accidentally deleted when updating modal headers)
> Fix bug: prof ratings missing from course modal

- api/config/constants.js
- api/controllers/catalog.controllers.js
- api/controllers/challenge.controllers.js
- api/package.json
- api/queries/catalog.queries.js
- api/routes/catalog.routes.js
- api/routes/challenge.routes.js
- api/server.js
- api/static/.gitignore
- api/utils.js
- docker/docker-compose.yml
- docker/prod-compose.yml
- Adds `/api/static` endpoint for accessing static files (NetID auth required):
- `/api/static/seasons.json`: list of all available seasons
- `/api/static/catalogs/{season}.json`: catalog per season
- Fetches and populates static files on API server start (set `OVERWRITE_CATALOG` environment parameter to update each catalog file, otherwise existing catalogs are skipped)
- Adds `/api/catalog/refresh` endpoint to refresh the catalog remotely. Can be called without authentication in development, otherwise set `FERRY_SECRET` in environment and specify `x-ferry-secret` header when calling.
> Static catalog

- frontend/src/pages/Search.module.css
Someone complained that the search box is really hard to see in dark mode - this is a quick fix for it, but we can also just reject and wait for #201 first
> Search box style changes

- frontend/src/components/SearchResults.js
- frontend/src/components/SearchResultsItem.js
Avoiding pre-computing it should make it faster, especially when viewing a list
Would probably be even better to split grid and list into two different components tho
> Generate grid html on the fly

- frontend/src/components/CourseConflictIcon.js
If the conflict icon is to mean anything and not be ignored, we should only show it when we're sure there's actually a conflict.
> Don't warn about invalid course times

- frontend/src/utilities.js
-Sort by number of FB friends instead of their names
Can't rlly test this cuz I only have 1 other account, but it should work
> Fix sortby FB friends bug

- frontend/src/pages/Search.js
- frontend/src/pages/Search.module.css
-Don't preserve visibility of search form
-Fix bug where the "show search form" icon isn't clickable on displays where the form is taller than the screen height
-Use overall same professor ratings in overall rating slider
-Visually update rating sliders when resetting filters
Issue was the positioning of the form being weird when the screen is too short, causing the icon to be placed behind something.
> Fix search form bugs

- frontend/src/components/CourseModalOverview.js
- frontend/src/components/CourseModalOverview.module.css
Toggle between eval filters using arrow keys on focus. Should I add some UI indication that the user has focused on the multitoggle?
> Make eval filter multitoggle focusable

- frontend/src/Globals.js
- frontend/src/components/WorksheetToggleButton.js
- frontend/src/user.tsx
Make sure userRefresh and fbRefresh return a promise, even in the case of network errors, and avoid throwing unhandled exceptions.
> Error handling

- docs/getting-started.md
added instructions to clone repository in linux filesystem. this does several things:
> Updated Windows dev environ setup instructions

- frontend/src/pages/Search.js
- Global hotkeys in search bar no longer active when modal is open, allowing ctrl-f search.
> Conditional hotkeys

- frontend/.gitignore
- frontend/src/components/CourseModalOverview.js
- frontend/src/components/CourseModalOverview.module.css
- frontend/src/components/SearchResultsGridItem.js
- frontend/src/components/SearchResultsItem.js
- frontend/src/pages/Search.js
**Primary Issue**
* Show all historical courses in the modal even if they don't have evaluations. Relevant issue (in more detail): https://github.com/coursetable/coursetable/issues/639
**Secondary Issues (see linked issues)** 
* Show course conflict icon when scrolling
* Add generated files from graphql to gitignore
* Add toggle to hide discussion sections in the search panel
> Show all courses on modal (and other optimizations)

- frontend/src/App.js
- frontend/src/components/CourseModalOverview.js
- frontend/src/components/CourseModalOverview.module.css
- frontend/src/components/MeDropdown.tsx
- frontend/src/components/Navbar.tsx
- frontend/src/pages/FAQ.tsx
- frontend/src/pages/Search.js
Minor updates for when we roll out the new semester:
* Set default season to Fall 2021 in the search bar
* Remove old coursetable link from the user dropdown
* Update banner to link to the coursetable LinkedIn page
* Set hover pointer to default for courses with no evals
* Hide courses without evals from current and future seasons in the course modal
(Done. See linked issues for details.)
> Small updates

- api/package.json
- api/src/auth/auth.handlers.ts
- api/src/auth/auth.routes.ts
- api/src/canny/canny.handlers.ts
- api/src/config.ts
- api/src/facebook/facebook.handlers.ts
- api/src/posthog.d.ts
- api/src/user/user.handlers.ts
- api/yarn.lock
- docker/docker-compose.yml
- docker/prod-compose.yml
Adds PostHog analytics to backend events. Because we are integrated with Yalies.io, this means we also track and store info such as year, residential college, graduation, etc., allowing us to get much more detailed user analytics than before (we only have NetIDs from frontend analytics).
Also mitigates the issue of PostHog being blocked by certain adblockers.
> PostHog backend analytics

- frontend/src/pages/Search.js
Summer course numbers are prefixed with an 's' and not matched by our tokenizer right now, so this adds an exception. (also fixes certain lab courses in normal seasons).
> Fix summer codes matching

- frontend/src/components/GenerateICS.tsx
- frontend/src/components/Navbar/MeDropdown.tsx
Coursetable keeps exporting Spring 2021 Courses. This PR updates the course export function (which uses hardcoded season + date boundaries + breaks) and the calling function from the dropdown to the Spring 2022. 
I'm making this PR because it was easier emotionally easier to clone + grep + change than to make my own schedule calendar events because I hate that with a burning passion.
> Update Calendar export from Spring 2021 to Spring 2022

- .github/workflows/ci.yml
- api/package.json
- api/prisma/schema.prisma
- api/src/auth/auth.handlers.ts
- api/src/facebook/facebook.handlers.ts
- api/src/user/user.handlers.ts
- frontend/src/App.jsx
- frontend/src/components/Footer.tsx
- frontend/src/components/Navbar/Navbar.tsx
- frontend/src/components/Navbar/NavbarCatalogSearch.tsx
- frontend/src/components/Navbar/NavbarWorksheetSearch.tsx
- frontend/src/components/Search/ListGridToggle.tsx
- frontend/src/components/Search/Popout.tsx
- frontend/src/components/Search/Results.jsx
- frontend/src/components/Search/ResultsColumnSort.tsx
- frontend/src/components/Search/ResultsGridItem.jsx
- frontend/src/components/Search/ResultsGridItem.module.css
- frontend/src/components/StyledComponents.tsx
- frontend/src/components/Themes.ts
- frontend/src/components/Worksheet/WorksheetCalendar.tsx
- frontend/src/components/Worksheet/WorksheetCalendarList.tsx
- frontend/src/components/Worksheet/WorksheetCalendarListItem.module.css
- frontend/src/components/Worksheet/WorksheetCalendarListItem.tsx
- frontend/src/pages/About.module.css
- frontend/src/pages/About.tsx
- frontend/src/pages/FAQ.module.css
- frontend/src/pages/FAQ.tsx
- frontend/src/pages/Worksheet.jsx
- frontend/src/styled.d.ts
Instead of instantaneously switching between light and dark mode, there is now a duration to decrease how jarring it is. This duration is in a centralized location (`lightTheme.trans_dur`/`darkTheme.trans_dur` in `frontend/src/components/Themes.ts`).
> Add theme transition duration to components

- api/src/config.ts
Add support for http://localhost and .yaleapps.com domains in CORS configuration
> Expand CORS to http localhost and .yaleapps.com

- api/README.md
- api/src/challenge/challenge.controllers.ts
- frontend/src/pages/FAQ.tsx
- frontend/src/pages/Privacy.tsx
Many in the '27 Discord server have realized that first-years signing onto CourseTable for the first time are unable to complete verification due to the OCE link being updated from the old `https://oce.app.yale.edu/oce-viewer/studentSummary/index?term_code=<CODE>` to `https://oce.app.yale.edu/ocedashboard/studentViewer/courseSummary?crn=<CRN>&termCode=<CODE>`. This PR updates the links throughout this repo.
I also have found that the "Overall Assessment" evaluation question seems to correspond to the question ID `YC404` in many, if not all, cases. Therefore, figuring out a way to leverage that query param could lead users directly to the question page, removing the extra step of reading through the questions list and clicking on the correct one to see the chart. However, the link for that …
> fix OCE links

- frontend/src/components/Notice.tsx
> Removed a disturbing margin wrapping the notice component

- frontend/src/App.jsx
Not to nitpick the header for a second time in a row, but this wording implied to me that working on CourseTable is a job, which may turn some people away.
> Change banner wording: work for -> work on

- frontend/src/contexts/searchContext.tsx
The "hide discussion sections" button currently checks whether the class name is "Discussion Section." This change checks whether the Section field is all letters, which is only true of discussion sections.
> Fix "Hide discussion sections" button

- .github/workflows/ci.yml
I don't know why, despite all the dependabot PRs, we get zero bumps for the GHA. This is the first step to fixing the GH actions.
> chore: bump GitHub actions

- frontend/src/components/CourseModal/CourseModalOverview.jsx
Fixes https://feedback.coursetable.com/bugs/p/sort-past-syllabi-chronologically
Before:
After:
It's mostly because of the missing `key` prop, but the sort function is wrong too, so I fixed both.
> fix: display past syllabi in reverse chronological order properly

- frontend/src/components/GenerateICS.tsx
- frontend/src/components/Worksheet/WorksheetCalendar.tsx
- frontend/src/components/Worksheet/WorksheetMobileCalendar.tsx
- frontend/src/utilities/courseUtilities.tsx
We have classes that happen before 8am. These classes are wrongly "fixed" to happen in the afternoon. Fixes https://coursetable.canny.io/admin/feedback/bugs/p/early-classes-show-up-in-the-evening-on-the-calendar
> fix: do not "fix" class time before 8

- frontend/src/components/Worksheet/GoogleCalendarSync/utils.ts
Prevent the same time slot from being registered twice (once as a new time)
> fix: only register each time slot once in gcal

- frontend/src/App.tsx
- frontend/src/Globals.tsx
- frontend/src/components/Navbar/Navbar.tsx
- frontend/src/contexts/themeContext.tsx
- frontend/src/main.tsx
This enables a few things:
1. You can use `{ theme } = useTheme()` anywhere and get the color theme, which could enable, for example, loading different images
2. We don't use hacks to pass down the `toggleTheme` prop
> refactor: make theme a global context

- frontend/src/components/Worksheet/WorksheetStats.tsx
The previous boundaries were totally made up, and after some trials I realized a realistic worksheet probably cannot get over 20 total workload, so this change makes the colors more indicative.
> fix: make total workload color map more reasonable

- api/dev-compose.yml
- api/entry.sh
- api/package.json
- api/prod-compose.yml
Fixes the issue where prod had to be deployed with `npm start` in entry.sh instead of `npm start:prod`
Also changed port routing to use doppler env vars instead of hardcoding. This is also accompanied with a doppler port var change, which will need careful monitoring when deployed on prod.
New port routes tested with prod->local emulation doppler config.
> fix: proper prod entry and env var port routing

- api/mysql/database.sql
- api/prisma/schema.prisma
- api/src/auth/auth.handlers.ts
- api/src/canny/canny.handlers.ts
- api/src/friends/friends.handlers.ts
- api/src/user/user.handlers.ts
- docs/api.md
- frontend/src/components/Worksheet/WorksheetToggleButton.tsx
This is a one-off migration. Otherwise the mix of `net_id` and `netId` is just going to cause more pain int the future.
> refactor(api): use camelCase for all DB fields

- frontend/src/components/Notice.tsx
This uses a single storage key instead of requesting a new storage key each time, which means we don't have to clear previous slots.
> refactor: use banner storage strategy that's not linear-growing

- frontend/src/App.tsx
- frontend/src/components/CourseModal/CourseModal.tsx
- frontend/src/utilities/display.tsx
- frontend/vite.config.ts
Part of an effort to reduce bundle size. This PR makes all page components lazy-loaded, which means unless you are on the respective page, the respective code won't be loaded at all. This speeds up first page load speed, and completely avoids loading heavy dependencies like `graphiql` for 99% of our users.
Before:
After:
The total size is the same, but note how the main bundle is significantly smaller, and chunks can be loaded on-demand only.
> feat: lazy-load route components

- frontend/src/App.tsx
This started as a bug fix, because I realized when you are logged in but don't have evals, and you go directly to coursetable.com/worksheets, you will have an infinite redirect loop. (`/worksheet` sends you to `/worksheetlogin` if you don't have evals, but `/worksheetlogin` sends you to `/worksheet` as long as you are logged in).
After a while, I realized I can make the process more straightforward.
> refactor: rework login UX

- frontend/src/utilities/calendar.ts
the colorid will no longer go to infinity, so it will always be valid.
> fix: cycle gcal event colorId

- frontend/src/components/Search/Results.tsx
- frontend/src/components/Worksheet/WorksheetList.tsx
- frontend/src/pages/Search.tsx
Fix https://github.com/coursetable/coursetable/issues/1444
> fix: restore to previous catalog view mode when resizing to desktop (instead of staying in grid)

- frontend/src/Globals.tsx
- frontend/src/components/Search/CourseConflictIcon.tsx
- frontend/src/contexts/searchContext.tsx
Currently we always use the main worksheet, which looks non-ideal because I may be bluebooking using another worksheet.
> fix: consistently use the currently viewed worksheet to calculate conflicts

- frontend/src/components/Search/Results.module.css
- frontend/src/components/Search/Results.tsx
- frontend/src/components/Search/ResultsCols.module.css
- frontend/src/components/Search/ResultsHeaders.tsx
- frontend/src/components/Search/ResultsItem.module.css
- frontend/src/components/Search/ResultsItem.tsx
Fully reactive to window resizing, works without JS, much faster and smoother transitions.
> refactor: use CSS instead of JS to calcalate column width

- frontend/src/contexts/searchContext.tsx
- frontend/src/utilities/course.ts
This PR avoids two courses from comparing equal in most cases. If the criterion doesn't return an order (for example, when sorting by rating), we default to sorting by season, course code, and section, which makes sure that no matter what intrinsic order these courses have in the first place, the returned order is always consistent.
> feat: course sorting should be stable and consistent

- frontend/src/pages/FAQ.tsx
The general sentiment is that there's absolutely no need for prefrosh to have access if they can't on official Yale websites.
> docs: add FAQ entry for prefrosh access granting

- frontend/src/components/CourseModal/EvaluationRatings.tsx
- frontend/src/components/CourseModal/EvaluationResponses.tsx
- frontend/src/components/CourseModal/RatingsGraph.tsx
- frontend/src/contexts/searchContext.tsx
- frontend/src/generated/graphql.schema.json
- frontend/src/generated/graphql.ts
- frontend/src/generated/infoAttributes.json
- frontend/src/queries/queries.graphql
- frontend/src/utilities/constants.ts
Use the tags/question text returned by the api, instead of manually building our own text table.
> feat: display all eval questions in course modal

- frontend/src/components/CourseModal/CourseModal.tsx
- frontend/src/components/CourseModal/CourseModalOverview.tsx
- frontend/src/components/CourseModal/OverviewInfo.tsx
- frontend/src/components/CourseModal/OverviewRatings.tsx
- frontend/src/generated/graphql.ts
- frontend/src/queries/queries.graphql
- frontend/src/utilities/display.tsx
Fix https://github.com/coursetable/coursetable/issues/1548.
Getting rid of `computed_listing_info` helps us re-think the course relationships, as it no longer blurs the line between courses and listings. We now always list _courses_, not _listings_.
> refactor: get rid of computed_listing_info in course modal queries

- frontend/src/pages/Challenge.tsx
- frontend/src/pages/FAQ.tsx
We receive too many emails from prefroshes; they are clearly not reading our FAQ.
> docs: make the prefrosh FAQ link PROMINENT AND CLEAR

- frontend/src/components/CourseModal/CourseModal.tsx
A little polish to make the UI less confusing
> polish: bolden current course code in cross-listings

- frontend/src/App.tsx
They can already interact with worksheets on the catalog, but they can't actually use the worksheet page.
Maybe we should hide the statistics panel? My personal preference is to use a placeholder like the catalog.
> feat: allow authed but no evals users to view worksheets

- frontend/src/components/CourseModal/CourseModal.tsx
- frontend/src/components/CourseModal/CourseModalOverview.tsx
- frontend/src/components/CourseModal/OverviewInfo.module.css
- frontend/src/components/CourseModal/OverviewInfo.tsx
- frontend/src/components/CourseModal/OverviewRatings.tsx
- frontend/src/generated/graphql-types.ts
- frontend/src/queries/graphql-queries.graphql
- frontend/src/queries/graphql-queries.ts
Fixes https://github.com/coursetable/coursetable/issues/1451
I've tried the following:
- https://prereq-link.preview.coursetable.com/catalog?course-modal=202403-10123
- https://prereq-link.preview.coursetable.com/catalog?course-modal=202403-10807
- https://prereq-link.preview.coursetable.com/catalog?course-modal=202403-10811
- https://prereq-link.preview.coursetable.com/catalog?course-modal=202501-21364
- https://prereq-link.preview.coursetable.com/catalog?course-modal=202403-14304
- https://prereq-link.preview.coursetable.com/catalog?course-modal=202501-20177
> feat: link to course prereqs

- frontend/src/utilities/course.ts
Changing the filtering logic function of isGraduate from filter by the course number to the school.
> fix: filter graduate course using school

- bun.lock
- frontend/package.json
- frontend/src/components/Worksheet/CalendarEvent.tsx
- frontend/src/components/Worksheet/NavbarWorksheetSearch.tsx
- frontend/src/components/Worksheet/SeasonDropdown.tsx
- frontend/src/components/Worksheet/URLExportButton.tsx
- frontend/src/components/Worksheet/WorksheetCalendarList.tsx
- frontend/src/components/Worksheet/WorksheetHideButton.tsx
- frontend/src/components/Worksheet/WorksheetStats.tsx
- frontend/src/main.tsx
- frontend/src/pages/Worksheet.tsx
- frontend/src/slices/WorksheetSlice.ts
- frontend/src/store.ts
Relying on `memoize` from `proxy-memoize` instead of subscription pattern. Should resolve stack overflow edge cases while following a much more accurate memoization pattern.
> refactor: completely rework memoized values in zustand
