coursetable/coursetable

web/templates/NewSplash.tpl

In GitLab by @hsource on Sep 28, 2019, 09:53

Changed contact email to CourseTable Elilist

---

.gitmodules
README.md

Add crawler as a submodule

---

web/.gitignore
web/templates/AboutModal.ejs
web/templates/NewSplash.tpl
web/templates/NoticeModal.ejs
web/templates/NoticeModal.tpl

Added YCS credits, renamed some instances of YalePlus and Bluebook, changed instances of coursetable feedback email
Closes #41.

Updated CourseTable info and help tabs

---

web/GenerateCsv.php

Fix link in csv generation

---

web/Table.php
web/templates/BluebookPerUser.tpl

Add Facebook disconnect button

---

web/includes/Credentials.php
web/includes/CredentialsOverride.sample.php
web/includes/ProjectCommon.php

This patch has already been applied to the server.

Hotfix: Facebook credentials in prod

---

web/GenerateIcs.php

Fix ICS generation to account for classes without meeting times

---

web/GenerateIcs.php

Add text location to calendar generation

---

web/Timetable.php
web/templates/Main.tpl

Add Heap analytics

---

web/css/bluebook.css
web/js/initializetable.js
web/js/tabletools.js

Fix #32 
I just commented out the relevant code. Happy to remove instead if you all thing that's a better idea.

Remove 'row' column

---

frontend/src/components/MeDropdown.js
frontend/src/pages/Worksheet.js

-should prevent any hook order issues in worksheet.js

Make sure order of hooks never changes

---

frontend/src/App.js
frontend/src/components/FBDropdown.js
frontend/src/components/WorksheetRowDropdown.js
frontend/src/components/WorksheetSettingsDropdown.js
frontend/src/pages/Worksheet.js
frontend/src/queries/GetWorksheetListings.js

-Automatically redirect to /worksheet from /worksheetlogin if the user is logged in
-Display FB friends in alphabetical order in all dropdowns

Worksheet Fixes

---

frontend/public/index.html
frontend/src/components/Navbar.js
frontend/src/pages/FAQ.js
frontend/src/pages/Home.js
frontend/src/pages/Landing.js
frontend/src/pages/Landing.module.css

- update home page boxes
- remove landing page features section
- FAQ link in navbar
- add ratings info to FAQs page

Content updates

---

frontend/src/components/WeekSchedule.css
frontend/src/components/WeekSchedule.js
frontend/src/pages/Worksheet.js

-Remove course time from a calendar event
-"Hide" other courses when ur hovering over a specific one by decreasing opacity
-Bring the event to the front on hover
-Slightly enlarge event on hover

Calendar updates

---

frontend/src/pages/FAQ.js

also remembered prettier formatting this time

fixed typo in FAQ ("anthing" to "anything")

---

frontend/src/components/WorksheetAccordion.js
frontend/src/pages/Worksheet.js
frontend/src/pages/Worksheet.module.css

-Remove @media(hover: none)
-Set max-height if not on mobile in a better way

Fix android worksheet bug

---

frontend/src/components/GenerateICS.js
frontend/src/components/MeDropdown.js
frontend/src/pages/Search.js

-Default to 202101 when searching catalog
-Default to 202101 when generating ics for worksheet

Default to 202101

---

frontend/public/index.html

Add preconnect

---

frontend/src/components/FBReactSelect.css
frontend/src/components/FBReactSelect.js
frontend/src/components/WeekSchedule.css
frontend/src/components/WorksheetRowDropdown.module.css

-Fix bug with showing 'x' or 'v' indicator for FB friends dropdown
-Constrain "Friends' courses" placeholder on one line and add ellipsis if too long
-Allow event boxes to scale outside of rbc-time-content container if on the edge

Fb dropdown updates

---

frontend/src/pages/Feedback.js

-Make email required
-Add permission to follow up switch

Updates to feedback form

---

frontend/src/components/MeDropdown.js
frontend/src/components/Navbar.js
frontend/src/pages/FAQ.js

-In Me Dropdown
-In FAQ question
-In Navbar for mobile

Add links to old coursetable

---

frontend/src/components/CourseModalOverview.js

-Add number of evals in each course, both, prof column to the multi toggle header
-Add n/a ratings to fill in blanks
-Evals in both column also show up in the course and prof columns

Course Modal Updates

---

frontend/src/components/CourseModalOverview.js
frontend/src/components/CourseModalOverview.module.css
frontend/src/components/SearchResultsItem.js
frontend/src/pages/Search.js
frontend/src/queries/Constants.js
frontend/src/queries/GetWorksheetListings.js
frontend/src/queries/QueryStrings.js

- Adds data to the modal for:
- `flag_info` (course information)
- `classnotes`
- `regnotes`
- `rp_attr` (reading period)
- `final_exam`
- Fixes enrollment numbers in catalog and modal.
- Adds ability to sort by (rating - workload) aka gut rating.

Course Info

---

frontend/src/App.js
frontend/src/components/CourseModal.js
frontend/src/components/FBReactSelect.js
frontend/src/components/SearchResults.js
frontend/src/components/SearchResults.module.css
frontend/src/components/SearchResultsItem.js
frontend/src/components/SeasonReactSelect.js
frontend/src/components/WeekSchedule.css
frontend/src/components/WeekSchedule.js
frontend/src/components/WorksheetAccordion.js
frontend/src/components/WorksheetExpandedList.js
frontend/src/components/WorksheetExpandedList.module.css
frontend/src/components/WorksheetList.js
frontend/src/components/WorksheetRowDropdown.js
frontend/src/components/WorksheetToggleButton.js
frontend/src/pages/Search.js
frontend/src/pages/Worksheet.js
frontend/src/pages/Worksheet.module.css

-Add season and fb select dropdowns to expanded worksheet view
-Add useMemos and useCallbacks everywhere
-Convert WeekSchedule and WorksheetList to functional components
-Don't blur other courses when hovering in the calendar
-Expand buttons always show on worksheet

Worksheet updates

---

frontend/src/components/CourseModal.js
frontend/src/components/WeekSchedule.js
frontend/src/components/WorksheetAccordion.js
frontend/src/components/WorksheetExpandedList.js

-Convert WorksheetAccordion to functional component
-Add useMemos and useCallbacks everywhere

Fix worksheet performance issues

---

frontend/src/Globals.js
frontend/src/components/DarkModeButton.js
frontend/src/components/Navbar.js
frontend/src/components/Navbar.module.css
frontend/src/components/SearchResults.module.css
frontend/src/components/WorksheetAccordion.js
frontend/src/components/WorksheetExpandedList.js
frontend/src/components/WorksheetExpandedList.module.css
frontend/src/components/WorksheetList.module.css
frontend/src/components/WorksheetRowDropdown.module.css
frontend/src/pages/Search.js
frontend/src/pages/Search.module.css
frontend/src/pages/Worksheet.js
frontend/src/pages/Worksheet.module.css
frontend/src/styles/common.module.css
frontend/src/utilities.js

-Center dark mode toggle
-Shorten wordmark height
-Make navbar fixed

Navbar fixes

---

frontend/src/App.js

Redirect /Table to catalog

---

frontend/src/components/CourseModalOverview.js
frontend/src/components/CustomSelect.js
frontend/src/components/FBReactSelect.js
frontend/src/components/MeDropdown.js
frontend/src/components/SearchResults.js
frontend/src/components/StyledComponents.js
frontend/src/components/WeekSchedule.js
frontend/src/components/WorksheetAccordion.js

this also improves worksheet performance a bit cuz it cuts down on the calendar rerenders

Fix react warnings

---

frontend/src/reportWebVitals.js

Avoids adding another chunk file

Don't lazy-load web-vitals

---

frontend/src/components/WeekSchedule.js

Hiding course completely removes it from calendar, so other courses expand to take up missing space

Fix Hide Course

---

frontend/src/components/StyledComponents.js
frontend/src/pages/Feedback.js
frontend/src/pages/Feedback.module.css

-Convert type selection to radio buttons
-Change Feedback description label and placeholders

Update feedback form

---

frontend/src/components/Themes.ts
frontend/src/pages/Feedback.js
frontend/src/pages/Feedback.module.css

custom radio and switch buttons to match colors

Custom radio buttons

---

.vscode/settings.json
frontend/package.json
frontend/src/components/CustomSelect.tsx
frontend/src/components/DarkModeButton.tsx
frontend/src/components/FBLoginButton.tsx
frontend/src/components/StyledComponents.tsx
frontend/src/pages/About.tsx
frontend/src/react-app-env.d.ts
frontend/src/user.tsx
frontend/src/wdyr.ts
frontend/tsconfig.json
frontend/yarn.lock

More typescript

---

frontend/src/components/FBDropdown.tsx
frontend/src/pages/Worksheet.js

TODO: we should eventually remove this restriction

Don't display friends with no courses in mobile

---

frontend/src/components/CustomSelect.tsx
frontend/src/components/FerryProvider.tsx
frontend/src/components/SortByReactSelect.tsx
frontend/src/courseUtilities.tsx
frontend/src/queries/Constants.ts

- Add type parameter to CustomSelect
- Strongly type sort functionality

Additional types

---

api/server.js

Add caching headers for static files

---

frontend/package.json
frontend/src/components/CourseConflictIcon.tsx
frontend/src/components/Navbar.tsx
frontend/src/courseUtilities.tsx
frontend/src/pages/FAQ.tsx
frontend/src/utilities.tsx
frontend/tsconfig.json
frontend/yarn.lock

- Also adds a couple minor fixes elsewhere

Additional typescript conversion

---

api/package.json
api/src/catalog/catalog.utils.js
api/src/challenge/challenge.controllers.js
api/static/.gitignore
api/yarn.lock
docker/docker-compose.yml

Also makes API wait-for graphql-server when starting.

Switch from graphqurl to graphql-request in API

---

frontend/src/components/FBDropdown.tsx
frontend/src/components/FBReactSelect.js
frontend/src/components/NoCourses.tsx
frontend/src/components/WorksheetAccordion.js
frontend/src/components/WorksheetList.js

TODO for both worksheet list and mobile
-Improve empty worksheet state
-Always show all FB friends even if they don't have courses for this season

Better empty worksheet state and always show all fb friends

---

.github/workflows/ci.yml

Follows best practices: https://stackoverflow.com/a/58223363/5004662.

Use yarn frozen lockfile in CI

---

api/.prettierrc.yaml
frontend/.prettierrc.yaml
proxy/.prettierrc.yaml

There was another part of this that I accidentally pushed directly to master

Fix linting

---

frontend/src/components/CatalogResults.js
frontend/src/components/CatalogResultsItem.js
frontend/src/components/SearchResultsGridItem.js
frontend/src/components/SearchResultsGridItem.module.css
frontend/src/components/Themes.ts
frontend/src/components/WorksheetToggleButton.js
frontend/src/styled.d.ts

Catalog result changes

---

frontend/src/components/CourseConflictIcon.tsx
frontend/src/courseUtilities.tsx

Just a small commit for my first pull request, but let me know if I'm doing anything wrong. Thanks!

Update course conflict icon to show conflicting/cross-listed classes

---

frontend/.prettierignore
frontend/package.json
frontend/src/Globals.tsx
frontend/src/components/Navbar/Navbar.tsx
frontend/src/components/Providers/FerryProvider.tsx
frontend/src/components/Search/Results.js
frontend/src/components/Search/ResultsColumnSort.tsx
frontend/src/components/Search/SortByReactSelect.tsx
frontend/src/components/Tutorial.tsx
frontend/src/components/Worksheet/WorksheetCalendar.tsx
frontend/src/components/Worksheet/WorksheetCalendarListItem.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/contexts/worksheetContext.tsx
frontend/src/react-lines-ellipsis.d.ts
frontend/src/utilities.tsx
frontend/src/wdyr.ts
frontend/yarn.lock

Disable reporting of ESlint warnings and fix/silence some errors.

Quieter frontend linting

---

frontend/src/pages/About.tsx
frontend/yarn.lock

Update about page

---

frontend/src/components/Search/ResultsGridItem.jsx

Currently not rendering right on Firefox

Fix grid view icons

---

frontend/src/App.jsx
frontend/src/components/Footer.tsx
frontend/src/pages/FAQ.tsx
frontend/src/pages/Privacy.module.css
frontend/src/pages/Privacy.tsx

Created an actual privacy policy page

Privacy-policy

---

frontend/src/App.jsx

JankTable has shut down, so I figured it might be time for this to go?

Remove outdated Notice

---

frontend/vite.config.ts

chore: display the right host in dev

---

api/docker-compose.yml

Missed this one—it's in a new file.

fix: another posthog occurrence

---

frontend/src/components/CourseModal/CourseModal.jsx
frontend/src/components/Providers/FerryProvider.tsx
frontend/src/contexts/worksheetContext.tsx

- Bug 1
- Bug 2
- Feature 1
- Feature 2
Fixes #

Updates course listing to include current worksheet.

---

api/Dockerfile
api/dev-compose.yml
api/docker-compose.yml
api/legacy/Dockerfile

Just a quick trimming of docker image fat in preparation for ECS migration.

chore: docker image size optimization

---

frontend/src/components/CourseModal/CourseModal.jsx
frontend/src/components/CourseModal/CourseModalOverview.jsx
frontend/src/components/Navbar/FBDropdown.tsx
frontend/src/components/Navbar/MeDropdown.tsx
frontend/src/components/Navbar/Navbar.tsx
frontend/src/components/Navbar/NavbarCatalogSearch.tsx
frontend/src/components/Providers/WindowDimensionsProvider.tsx
frontend/src/components/Search/CourseConflictIcon.tsx
frontend/src/components/Search/Popout.tsx
frontend/src/components/Search/Results.jsx
frontend/src/components/Search/ResultsColumnSort.tsx
frontend/src/components/Search/ResultsGridItem.jsx
frontend/src/components/Search/ResultsItem.jsx
frontend/src/components/Search/SortByReactSelect.tsx
frontend/src/components/Worksheet/CalendarEvent.tsx
frontend/src/components/Worksheet/WorksheetAccordion.tsx
frontend/src/components/Worksheet/WorksheetHideButton.tsx
frontend/src/components/Worksheet/WorksheetList.tsx
frontend/src/components/Worksheet/WorksheetToggleButton.tsx
frontend/src/pages/Challenge.tsx

I am doing this because callbacks are extremely hard to type while if they are inlined the parameter types can be inferred. This particularly applies to the files that are still JSX which I plan to upgrade to TSX.

refactor: inline some functions that are only used once

---

frontend/src/components/Navbar/WorksheetNumberDropdown.tsx
frontend/src/components/Worksheet/WorksheetAccordion.tsx

This PR lets you see your multiple worksheets on mobile

allow multiple on mobile

---

frontend/src/components/Worksheet/WorksheetToggleButton.tsx

- Bug 1
- Bug 2
- Feature 1
- Feature 2
Fixes #

worksheet list multiple

---

frontend/src/components/Navbar/MeDropdown.tsx
frontend/src/components/Navbar/NavbarWorksheetSearch.tsx
frontend/src/components/Worksheet/WorksheetToggleButton.tsx
frontend/src/contexts/userContext.tsx
frontend/src/contexts/worksheetContext.tsx
frontend/src/queries/GetWorksheetListings.tsx
frontend/src/utilities/courseUtilities.tsx

- Bug 1
- Bug 2
- Feature 1
- Feature 2
Fixes #

fix: remove logs

---

api/src/facebook/friends.handlers.ts

- Bug 1
- Bug 2
- Feature 1
- Feature 2
Fixes #

removed winston logs

---

frontend/src/pages/Privacy.tsx

Chore - need to add in order to obtain app verification from Google.
https://github.com/coursetable/coursetable/pull/1379

Add limited use disclosure to privacy policy

---

frontend/src/components/CourseModal/CourseModalOverview.jsx
frontend/src/components/GenerateICS.tsx
frontend/src/components/Providers/FerryProvider.tsx
frontend/src/components/Search/CourseConflictIcon.tsx
frontend/src/components/Worksheet/CalendarEvent.tsx
frontend/src/components/Worksheet/GoogleCalendarSync/GoogleCalendarButton.tsx
frontend/src/components/Worksheet/GoogleCalendarSync/utils.ts
frontend/src/components/Worksheet/WorksheetAccordion.tsx
frontend/src/components/Worksheet/WorksheetCalendar.tsx
frontend/src/components/Worksheet/WorksheetMobileCalendar.tsx
frontend/src/utilities/courseUtilities.tsx

This PR makes all times and locations considered by:
1. Conflict checking
2. Calendar view
3. Export ICS/GCal
4. Course modal
Before:
After:
Before:
After:

fix: display all class meet times

---

frontend/src/components/CourseModal/CourseModalOverview.jsx

Follow up to https://github.com/coursetable/coursetable/pull/1409

fix: display time in 12h in modal

---

frontend/src/components/Worksheet/GoogleCalendarSync/utils.ts

- Bug 1
- Bug 2
- Feature 1
- Feature 2
Fixes #

fix: add correct day to gcal

---

.github/workflows/preview_cd.yml
.github/workflows/preview_comment.yml
frontend/src/App.jsx
frontend/src/components/Worksheet/GoogleCalendarSync/GoogleCalendarButton.tsx

Fixes #1416 
(also fixes frontend lints)

fix: URL Encode Branch Names for Preview URLs

---

frontend/src/components/Navbar/NavbarWorksheetSearch.tsx

fix: prevent passing isTablet to DOM

---

frontend/src/App.jsx
frontend/src/components/CourseModal/CourseModal.jsx
frontend/src/components/Navbar/NavbarCatalogSearch.tsx
frontend/src/components/Search/Results.jsx
frontend/src/components/Search/ResultsGridItem.jsx
frontend/src/components/Search/ResultsItem.jsx
frontend/src/components/Worksheet/WorksheetAccordion.tsx
frontend/src/components/Worksheet/WorksheetCalendar.tsx
frontend/src/components/Worksheet/WorksheetCalendarListItem.tsx
frontend/src/components/Worksheet/WorksheetList.tsx
frontend/src/components/Worksheet/WorksheetMobileCalendar.tsx
frontend/src/components/Worksheet/WorksheetMobileCalendarListItem.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/contexts/worksheetContext.tsx
frontend/src/pages/Search.tsx
frontend/src/pages/Worksheet.jsx

feat: unique URL for each course modal

---

frontend/src/components/CourseModal/CourseModal.jsx
frontend/src/components/CourseModal/CourseModalOverview.jsx
frontend/src/components/Search/Results.css
frontend/src/components/Search/Results.jsx
frontend/src/components/Search/Results.module.css
frontend/src/components/Search/ResultsGridItem.jsx
frontend/src/components/Search/ResultsItem.jsx
frontend/src/components/Search/ResultsItem.module.css
frontend/src/components/Search/SortByReactSelect.tsx
frontend/src/components/Search/SortbyReactSelect.module.css
frontend/src/components/SkillBadge.module.css
frontend/src/components/SkillBadge.tsx
frontend/src/components/Worksheet/WorksheetAccordion.tsx
frontend/src/components/Worksheet/WorksheetStats.tsx
frontend/src/pages/About.tsx
frontend/src/pages/Challenge.tsx
frontend/src/pages/Graphiql.css
frontend/src/pages/Search.module.css
frontend/src/pages/Search.tsx

1. Always import the file as `styles`
2. Do not cross-import and extract component where possible

refactor: normalize how we use module CSS

---

frontend/src/components/CustomSelect.tsx
frontend/src/components/Search/PopoutSelect.tsx
frontend/src/components/Search/Searchbar.tsx

Greatly reduces code duplication too!

refactor: remove ts-nocheck

---

.github/workflows/preview_cd.yml

fix: url truncation and ssl cert issuance for preview cd

---

frontend/src/components/Navbar/NavbarCatalogSearch.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/pages/Search.tsx

feat: hide conflicting courses

---

frontend/src/components/Worksheet/GoogleCalendarSync/GoogleCalendarButton.tsx
frontend/src/contexts/ferryContext.tsx
frontend/src/contexts/userContext.tsx
frontend/src/contexts/worksheetContext.tsx
frontend/src/pages/Worksheet.tsx
frontend/src/queries/GetWorksheetListings.tsx

Otherwise in Sentry, they always show up with type `<unknown>`.

refactor: make sure we always capture Error instances

---

frontend/src/components/CourseModal/CourseModalOverview.jsx
frontend/src/config.ts
frontend/src/contexts/worksheetContext.tsx

Now all year references live in the same file :)

refactor: move the last reference of year to config

---

frontend/src/components/CustomSelect.tsx
frontend/src/components/Navbar/NavbarCatalogSearch.tsx
frontend/src/components/Search/PopoutSelect.tsx

Follow-up to #1488; accidentally removed a prop.

fix: area/skills dropdown colors

---

api/dev-compose.yml
frontend/src/config.ts

Container port mapping and frontend API URL are synced with doppler port env var.

feat: dev port mapping syncs with doppler

---

api/src/auth/auth.routes.ts
api/src/catalog/catalog.controllers.ts
api/src/challenge/challenge.controllers.ts
api/src/challenge/challenge.routes.ts
api/src/user/user.handlers.ts
docs/api.md
docs/how-to-deploy.md
frontend/src/pages/Challenge.tsx
frontend/src/utilities/calendar.ts

This adds preliminary API shape description. This should help us:
1. Develop shared schemas and type defs
2. Refactor our `axios` usage to native `fetch`
3. Prevent mistakes like https://github.com/coursetable/coursetable/commit/607cde193223e2b3753267e1a448f2e4213b022d
There aren't many actual code changes in this PR. Significant improvements are deferred to the future.

docs: add basic documentation for all REST APIs

---

.eslintrc.js
api/src/auth/auth.handlers.ts
api/src/auth/auth.routes.ts
api/src/canny/canny.handlers.ts
api/src/catalog/catalog.utils.ts
api/src/challenge/challenge.handlers.ts
api/src/config.ts
api/src/friends/friends.handlers.ts
api/src/logging/morgan.ts
api/src/user/user.handlers.ts

After we have better types, we can finally do this.

chore: enable all ESLint rules in api

---

api/src/auth/auth.routes.ts
api/src/challenge/challenge.handlers.ts
docs/api.md
frontend/src/pages/Challenge.tsx
frontend/src/utilities/display.ts

First part to get off axios. This time it's challenge and logout.
Has some minor API refactors.

refactor: migrate to fetch, part I

---

api/src/friends/friends.handlers.ts
api/src/user/user.handlers.ts
docs/api.md
frontend/src/components/CourseModal/CourseModalOverview.tsx
frontend/src/components/Navbar/FriendsDropdown.tsx
frontend/src/components/Navbar/NavbarWorksheetSearch.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/contexts/userContext.tsx
frontend/src/contexts/worksheetContext.tsx
frontend/src/utilities/course.ts

I'm still not totally satisfied by our friends feature (for example, we don't actually reject friend requests, and there are a ton of ways to fail the prisma queries) but at least this makes the API more sane.

refactor: rework friends API design

---

frontend/src/App.tsx

temporary solution for tracking if our eval suggest link gets clicked

feat: add sentry (temp) logs for eval click

---

frontend/src/App.tsx
frontend/src/Globals.tsx
frontend/src/contexts/ferryContext.tsx
frontend/src/contexts/userContext.tsx

Should fix a lot of 401 errors.

fix: do not fetch data until auth confirmed

---

frontend/src/components/Notice.tsx
frontend/src/components/Worksheet/WorksheetToggleButton.tsx
frontend/src/utilities/browserStorage.ts

Session storage / Local storage is unavailable in Safari private mode as well as potentially other privacy modes.
In addition, I've delayed the retrieval of local storage to after page load. This is needed for server-side rendering.
Asking for feedback on whether the UX is good. Please add some filters and then reload the page.

fix: browser storage may be inaccessible

---

frontend/src/App.tsx

Let's test if this produces any unwanted behavior.

feat: code-split tutorial component

---

.prettierignore
api/src/catalog/catalog.utils.ts
frontend/src/components/Navbar/NavbarWorksheetSearch.tsx
frontend/src/contexts/ferryContext.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/contexts/worksheetContext.tsx
frontend/src/generated/graphql.schema.json
frontend/src/generated/seasons.json

refactor: simplify seasons data structure

---

frontend/src/contexts/ferryContext.tsx

This PR fixes two common Sentry exceptions:
1. failed to fetch course data for 202401. Unauthorized
2. Too many pending tasks in queue load-202401
The first is because we fire the request before the user gets redirected to the challenge page.  We just need to change the check from "logged in" to "has evals".
The second is trickier. In the long term we want to get rid of async-lock and make sure we always only fire one request per season. For now, I've simply utilized the `courseLoadAttempted` set. I'm not sure why the comment says not to use that, but let's see if it works.

fix: common data fetching problems in catalog

---

frontend/src/utilities/calendar.ts

- Bug 1
- Bug 2
- Feature 1
- Feature 2
Fixes #

fix: delete gcal colors

---

frontend/src/components/Navbar/NavbarCatalogSearch.tsx
frontend/src/components/Search/ResultsColumnSort.tsx
frontend/src/components/Search/SortByReactSelect.tsx
frontend/src/components/Worksheet/WorksheetList.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/pages/Search.tsx
frontend/src/utilities/common.ts

There is now much less copy/pasted code for each search state and it should be easier to add more filters in the future.

refactor: rework search states, reduce copy pasta

---

frontend/src/components/Navbar/Navbar.tsx
frontend/src/components/Navbar/NavbarCatalogSearch.tsx
frontend/src/components/Search/CourseConflictIcon.tsx
frontend/src/components/Search/Popout.tsx
frontend/src/components/Search/Results.tsx
frontend/src/contexts/ferryContext.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/pages/Search.tsx

Bug fixes and refactors, guided by ESLint

fix: search filter fixes

---

frontend/src/components/Navbar/NavbarCatalogSearch.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/pages/Search.tsx
frontend/src/utilities/course.ts

Memoize each processed query independently.

refactor: get rid of searchConfig indirection

---

frontend/src/components/Navbar/NavbarCatalogSearch.tsx
frontend/src/components/Search/Results.tsx
frontend/src/components/Search/ResultsColumnSort.tsx
frontend/src/components/Search/SortByReactSelect.tsx
frontend/src/components/Worksheet/WorksheetList.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/utilities/constants.ts
frontend/src/utilities/course.ts

Use a key-value store so that we avoid arbitrary indices.

refactor: better sortByOptions data structure

---

frontend/src/App.tsx
frontend/src/components/Navbar/MeDropdown.tsx
frontend/src/components/Navbar/Navbar.tsx
frontend/src/components/Tutorial.tsx
frontend/src/index.css

Fix https://github.com/coursetable/coursetable/issues/1566

fix: make it possible to hide tutorial at every step

---

frontend/vite.config.ts

feat: CSS code-splitting

---

frontend/src/components/Navbar/NavbarCatalogSearch.tsx
frontend/src/components/Navbar/NavbarWorksheetSearch.tsx
frontend/src/components/Search/MobileSearchForm.tsx
frontend/src/components/Search/Popout.tsx
frontend/src/components/Search/ResultsHeaders.tsx
frontend/src/contexts/searchContext.tsx

Reduce some boilerplate and fix a few behaviors

refactor: further simplify search data structure

---

frontend/src/components/CourseModal/CourseModalOverview.module.css
frontend/src/components/Navbar/Navbar.module.css
frontend/src/components/Navbar/Navbar.tsx
frontend/src/components/Navbar/NavbarCatalogSearch.module.css
frontend/src/components/Navbar/NavbarCatalogSearch.tsx
frontend/src/components/Navbar/NavbarWorksheetSearch.module.css
frontend/src/components/Navbar/NavbarWorksheetSearch.tsx
frontend/src/components/Notice.module.css
frontend/src/components/Search/Popout.module.css
frontend/src/components/Search/Popout.tsx
frontend/src/components/Search/ResultsGridItem.module.css
frontend/src/components/Search/ResultsGridItem.tsx
frontend/src/components/Search/ResultsHeaders.module.css
frontend/src/components/Search/ResultsHeaders.tsx
frontend/src/components/Search/ResultsItem.module.css
frontend/src/components/Search/ResultsItem.tsx
frontend/src/components/StyledComponents.tsx
frontend/src/components/Worksheet/CalendarEvent.module.css
frontend/src/components/Worksheet/WorksheetCalendarListItem.module.css
frontend/src/components/Worksheet/react-big-calendar-override.css
frontend/src/contexts/windowDimensionsContext.tsx
frontend/src/index.css
frontend/src/pages/About.module.css
frontend/src/pages/Challenge.module.css
frontend/src/pages/FAQ.module.css
frontend/src/pages/Join.module.css
frontend/src/pages/Privacy.module.css
frontend/src/pages/releases/fall23.module.css
frontend/src/utilities/display.tsx

Next step towards no styled-components. This time `breakpoints()` is gone.

refactor: migrate breakpoints logic to pure CSS

---

api/mysql/database.sql
api/prisma/schema.prisma
api/src/friends/friends.handlers.ts
api/src/user/user.handlers.ts
docs/api.md
frontend/src/components/Navbar/NavbarWorksheetSearch.tsx
frontend/src/components/Search/CourseConflictIcon.tsx
frontend/src/components/Worksheet/WorksheetNumberDropdown.tsx
frontend/src/components/Worksheet/WorksheetToggleButton.tsx
frontend/src/contexts/ferryContext.tsx
frontend/src/contexts/userContext.tsx
frontend/src/contexts/worksheetContext.tsx
frontend/src/utilities/course.ts

Prevent unnecessary type-casting. Can't test this because it needs backend changes too.

refactor: API should send worksheet data in numbers if possible

---

docs/api.md
frontend/src/components/Worksheet/CalendarEvent.tsx
frontend/src/components/Worksheet/WorksheetCalendar.tsx
frontend/src/contexts/ferryContext.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/contexts/worksheetContext.tsx
frontend/src/utilities/calendar.ts
frontend/src/utilities/common.ts

Using a separate data struct for ease of management

refactor: avoid adding color to the Listing data structure

---

api/src/user/user.handlers.ts
frontend/src/components/Worksheet/CalendarEvent.tsx
frontend/src/components/Worksheet/WorksheetCalendar.tsx
frontend/src/components/Worksheet/WorksheetCalendarList.tsx
frontend/src/components/Worksheet/WorksheetList.tsx
frontend/src/components/Worksheet/WorksheetStats.tsx
frontend/src/contexts/ferryContext.tsx
frontend/src/contexts/worksheetContext.tsx
frontend/src/utilities/calendar.ts
frontend/src/utilities/constants.ts
frontend/src/utilities/course.ts

https://github.com/coursetable/coursetable/pull/1583

refactor: preparatory work for DB worksheet data

---

frontend/src/components/CourseModal/CourseModalOverview.module.css
frontend/src/components/CourseModal/CourseModalOverview.tsx
frontend/src/components/CourseModal/RatingsGraph.tsx
frontend/src/components/Navbar/NavbarWorksheetSearch.tsx
frontend/src/components/Worksheet/FriendsDropdown.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/utilities/constants.ts
frontend/vite.config.ts

Replace `push` with `map` where possible

refactor: avoid mutating array methods

---

frontend/src/components/Search/Results.tsx
frontend/src/components/Search/ResultsItem.tsx
frontend/src/components/Worksheet/WorksheetList.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/pages/Search.tsx
frontend/src/utilities/course.ts

If a person adds a course to three worksheets it shows up three times.

fix: "#friends" should deduplicate by friends name

---

api/src/auth/user.d.ts
frontend/src/contexts/userContext.tsx

refactor: validate all API responses with zod

---

frontend/src/components/Navbar/MeDropdown.tsx
frontend/src/components/Search/ResultsGridItem.module.css
frontend/src/components/Search/ResultsGridItem.tsx
frontend/src/components/Search/ResultsHeaders.tsx
frontend/src/components/Search/ResultsItem.tsx
frontend/src/components/SkillBadge.tsx
frontend/src/components/Worksheet/WorksheetStats.module.css
frontend/src/components/Worksheet/WorksheetStats.tsx

Minor refactors, improve maintainability.

refactor: deduplicate some code

---

frontend/src/components/Navbar/MeDropdown.tsx
frontend/src/components/Navbar/Navbar.tsx
frontend/src/components/Worksheet/WorksheetToggleButton.tsx
frontend/src/contexts/ferryContext.tsx
frontend/src/contexts/userContext.tsx
frontend/src/pages/Challenge.tsx
frontend/src/utilities/api.ts
frontend/src/utilities/display.tsx

This enables us to swap this file through Vite module resolution. Part of https://github.com/coursetable/coursetable/issues/1217.

refactor: extract all API calls to a single file

---

frontend/src/App.tsx
frontend/src/Globals.tsx
frontend/src/components/Navbar/MeDropdown.tsx
frontend/src/components/Navbar/Navbar.tsx
frontend/src/components/Tutorial.tsx
frontend/src/contexts/tutorialContext.tsx
frontend/src/main.tsx

refactor: make tutorial state a context

---

frontend/src/App.tsx
frontend/src/components/Navbar/MeDropdown.tsx
frontend/src/components/Tutorial.tsx
frontend/src/components/Typography.tsx
frontend/src/contexts/tutorialContext.tsx

refactor: minimize tutorial context

---

frontend/src/components/Navbar/NavbarWorksheetSearch.tsx
frontend/src/contexts/userContext.tsx

Minor refactor in preparation of name searching

refactor: split worksheet navbar dropdowns

---

frontend/codegen.yml
frontend/package.json
frontend/src/components/CourseModal/CourseModal.tsx
frontend/src/components/CourseModal/CourseModalOverview.tsx
frontend/src/generated/graphql.ts
frontend/src/queries/queries.graphql
frontend/src/utilities/common.ts

Get rid of a lot of duplication, also fixed one type error.

refactor: greatly deduplicate GraphQL schema

---

frontend/src/components/Navbar/DarkModeButton.tsx
frontend/src/components/Navbar/Navbar.tsx
frontend/src/components/Navbar/NavbarWorksheetSearch.tsx
frontend/src/components/Search/ResultsItem.tsx

`useEffect` is slow and cause needless rerenders.

refactor: remove a few useless useEffect

---

frontend/src/contexts/searchContext.tsx

Part of https://github.com/coursetable/coursetable/issues/1453

feat: search location

---

frontend/src/components/Search/CustomSelect.tsx
frontend/src/components/Worksheet/CalendarEvent.module.css
frontend/src/components/Worksheet/CalendarEvent.tsx
frontend/src/components/Worksheet/WorksheetHideButton.tsx

fix #1611
could use some UI tweaks maybe

feat: add hide button to calendar events

---

frontend/src/App.tsx
frontend/src/components/CourseModal/CourseModalOverview.tsx
frontend/src/components/Search/ResultsGridItem.tsx
frontend/src/components/Search/ResultsItem.tsx
frontend/src/utilities/common.ts

polish: better public UI

---

api/src/catalog/catalog.queries.ts
api/src/catalog/catalog.utils.ts
api/src/server.ts
frontend/src/components/CourseModal/CourseModal.tsx
frontend/src/components/CourseModal/CourseModalOverview.tsx
frontend/src/contexts/ferryContext.tsx
frontend/src/generated/graphql.ts
frontend/src/queries/queries.graphql
frontend/src/utilities/api.ts
frontend/src/utilities/common.ts

Avoid fetching the same info twice, avoid two separate queries (by using parameters)

refactor: improve catalog fetching logic, fix types

---

frontend/src/components/CourseModal/EvaluationRatings.tsx
frontend/src/components/CourseModal/EvaluationResponses.tsx
frontend/src/components/CourseModal/RatingsGraph.module.css
frontend/src/components/CourseModal/RatingsGraph.tsx
frontend/src/generated/graphql.ts
frontend/src/queries/queries.graphql

Fix https://github.com/coursetable/coursetable/issues/1620

feat: show percentage of enrolled students who left review

---

frontend/src/config.ts
frontend/src/utilities/calendar.ts

A few enhancements to Gcal integration:
- transfer days (friday becoming monday) figured out
- spring 2025 calendar added
- due to popular demand, we add more details to the gcal events, specifically course + instructor name.

feat: gcal enhancement

---

frontend/src/components/Navbar/MeDropdown.tsx

A bit of a pet peeve lol, but this does seem to be a webdev convention. We could also consider making the rows gray-hoverable.
See Reddit and Twitch for example.

feat: make icons clickable in MeDropdown

---

frontend/src/components/Search/Results.tsx

Fix https://github.com/coursetable/coursetable/issues/1628

fix: fix scroll-up blackout bug

---

frontend/src/components/Navbar/NavbarWorksheetSearch.tsx

Reverts coursetable/coursetable#1658

Revert "fix: incoming friend reqs should not be clickable"

---

frontend/src/contexts/ferryContext.tsx
frontend/src/contexts/userContext.tsx
frontend/src/utilities/api.ts

dedupe some fetch code in friend api

refactor: dedupe some fetch code

---

frontend/src/components/Navbar/NavbarCatalogSearch.tsx
frontend/src/components/Search/MobileSearchForm.tsx
frontend/src/contexts/searchContext.tsx

Fix https://github.com/coursetable/coursetable/issues/1669
Clearly differentiate between "default" and "empty" states.

polish: rework filter reseting UX

---

frontend/src/components/CourseModal/CourseModalOverview.tsx

so people can understand what enrollment actually means

polish: more modal enrollment description

---

frontend/src/components/Search/CustomSelect.tsx

Fix https://github.com/coursetable/coursetable/issues/1674

fix: do not autoscroll dropdown menu into view

---

frontend/src/components/CourseModal/CourseModal.tsx
frontend/src/components/CourseModal/CourseModalOverview.tsx
frontend/src/components/CourseModal/OverviewInfo.tsx
frontend/src/components/CourseModal/OverviewRatings.tsx
frontend/src/components/Search/Results.tsx
frontend/src/components/Search/ResultsColumnSort.tsx
frontend/src/components/Search/ResultsGridItem.tsx
frontend/src/components/Search/ResultsHeaders.tsx
frontend/src/components/Search/ResultsItem.tsx
frontend/src/components/Search/ResultsItemCommon.tsx
frontend/src/components/Worksheet/CalendarEvent.tsx
frontend/src/components/Worksheet/WorksheetCalendarList.tsx
frontend/src/components/Worksheet/WorksheetCalendarListItem.tsx
frontend/src/components/Worksheet/WorksheetStats.tsx
frontend/src/components/Worksheet/WorksheetToggleButton.tsx
frontend/src/contexts/ferryContext.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/queries/api.ts
frontend/src/utilities/calendar.ts
frontend/src/utilities/course.ts

We no longer have any `computed_listing_info` structure left!

feat: use new catalog data

---

frontend/src/components/CourseModal/CourseModal.module.css
frontend/src/components/CourseModal/CourseModal.tsx
frontend/src/components/CourseModal/CourseModalOverview.tsx
frontend/src/components/CourseModal/OverviewRatings.tsx
frontend/src/utilities/display.tsx

Part of https://github.com/coursetable/coursetable/issues/1694

feat: links to cross-listings in modal

---

api/src/catalog/catalog.utils.ts
frontend/src/components/CourseModal/CourseModal.tsx

chose semi arbitrary dates for last updated though

polish: add date and better search terms to titles

---

frontend/src/components/CourseModal/OverviewRatings.tsx
frontend/src/components/Navbar/Navbar.module.css
frontend/src/components/Navbar/Navbar.tsx
frontend/src/components/Search/ResultsGridItem.tsx
frontend/src/components/Search/ResultsItem.tsx

Fix https://github.com/coursetable/coursetable/issues/1633. Granted https://github.com/coursetable/coursetable/issues/1703 would do the same but we can obviously have both.

feat: display challenge link when users need to do challenge

---

api/src/link-preview/link-preview.handlers.ts
frontend/src/pages/Join.tsx

docs: update joinus

---

frontend/src/App.tsx

@Josh-Cena do we want to add any click trackers or anything

chore: add user survey

---

frontend/src/components/Worksheet/FriendsDropdown.tsx
frontend/src/queries/api.ts
frontend/src/utilities/calendar.ts

chore: fix CI

---

api/src/user/user.handlers.ts
docs/api.md
frontend/src/components/Worksheet/ColorPickerButton.tsx
frontend/src/components/Worksheet/WorksheetToggleButton.tsx
frontend/src/contexts/worksheetContext.tsx
frontend/src/queries/api.ts

- Bug 1
- Bug 2
- Feature 1
- Feature 2
Fixes #

feat: implement worksheet hidden status syncing

---

api/src/catalog/catalog.queries.graphql
api/src/catalog/catalog.queries.ts
api/src/graphql-types.ts
frontend/graphql-codegen.ts
frontend/src/components/CourseModal/Header/InfoRow.tsx
frontend/src/components/CourseModal/OverviewPanel/OverviewInfo.tsx
frontend/src/components/Search/AdvancedPanel.tsx
frontend/src/contexts/searchContext.tsx
frontend/src/generated/graphql-types.ts
frontend/src/generated/graphql.schema.json
frontend/src/generated/infoAttributes.json
frontend/src/pages/Graphiql.tsx
frontend/src/queries/graphql-queries.graphql
frontend/src/queries/graphql-queries.ts
frontend/src/queries/graphql-types.ts
frontend/src/queries/schema-overrides.graphql
frontend/src/utilities/calendar.ts
frontend/src/utilities/constants.ts
frontend/src/utilities/course.ts

Complete our structured location parsing task

refactor: integrate course_meetings table, use instead of times_by_day

---

api/src/server.ts

- Bug 1
- Bug 2
- Feature 1
- Feature 2
Fixes #

chore: lax samesite for previews

---

api/src/catalog/catalog.queries.graphql
api/src/catalog/catalog.queries.ts

Update GraphQL queries to include `time_added` and `last_updated` columns in catalog.
Required to test #1803

graphql queries for catalog

---

frontend/src/slices/WorksheetSlice.ts

Fixes exotic worksheet view (by fixing creation of worksheet slice).
export worksheet as URL and view the exported worksheet.

fix: worksheet slice exoticWorksheet
